### ISSUE TITLE
E2e tests

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#104]
Please collect the cases and write an approach for running e2e tests.

Internally we agreed:

- To use built-in kubebuilder oportunity for running e2e tests
- Use kind to run one-time Kubernetes cluster in a pipeline
- @sergeyshevch suggested to implement smoke tests and run them as part of e2e

**Comment by hiddenmarten** [comment]
As a start case, it would be nice to implement a simple upscale test:
Deploy a minimalistic CR with replicas count as a 3, after that - check that the deployment was successful.
After a successful check for 3 replicas deployment upscale replicas count to 5 and repeat check cluster health.
After all - delete CR.

**Comment by sergeyshevch** [comment]
I suggest slightly more complex approach that will test simple end user lifecycle

- Deploy all requirements (cert-manager etcd)
- Deploy operator and its CRD
- Create kind:EtcdCluster with some simple settings
- Wait until ready
- Delete kind:EtcdCluster
- Delete operator
- Check that all resources was cleaned up

**Comment by hiddenmarten** [comment]
> I suggest slightly more complex approach that will test simple end user lifecycle
> 
> - Deploy all requirements (cert-manager etcd)
> - Deploy operator and its CRD
> - Create kind:EtcdCluster with some simple settings
> - Wait until ready
> - Delete kind:EtcdCluster
> - Delete operator
> - Check that all resources was cleaned up

I don't quite get how installation/deletion of operator test any operator functionality...

**Comment by Kirill-Garbar** [comment]
I think that installation and deinsallation of operator can take place, but not with golang tests. Let's make it separate: test of operator functionality and tests of helm chart.
