### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#105]
Please create a DEVELOPMENT.md file where we will collect all the infromation about our project development.

Initially it should contain information about how we make releases.
Just an infromartion that we use standard Github release feature.

Additionally It can also include link to https://github.com/aenix-io/etcd-operator/blob/main/CONTRIBUTING.md

**Comment by kvaps** [comment]
link https://github.com/aenix-io/etcd-operator/issues/103

**Comment by sergeyshevch** [comment]
We already have https://github.com/aenix-io/etcd-operator/blob/main/HOW-TO-START-DEVELOPMENT.md but I guess its better to move it into docs site
