### ISSUE TITLE
Write basic etcd-operator logic

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#13]
We agreed on the folowing logic:

- Create configmap with env `ETCD_INITIAL_CLUSTER_STATE=new`
- Create StatefulSet with needed amount of replicas and `envFrom: <configmap>`, and `podManagementPolicy: Parallel`
- Wait unitl all replicas become ready
- Update configmap to  `ETCD_INITIAL_CLUSTER_STATE=existing`
- Consider that cluster as bootstrapped

currently locked by https://github.com/aenix-io/etcd-operator/issues/9

**Comment by apten-fors** [comment]
Don't forget about persistence:
`spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
`

**Comment by kvaps** [comment]
> `podManagementPolicy: Parallel`

I think this policy should not be controlled by user, as it is part of operator logic

> ```
>   persistentVolumeClaimRetentionPolicy:
>     whenDeleted: Retain
>     whenScaled: Retain
> ```

Do you have any examples how are other operator define this spec?
Let's discuss it at the next community meeting.
