### ISSUE TITLE
[API] not using core/v1 pod spec

### ISSUE THREAD

**Issue by Bo0km4n** [aenix-io/etcd-operator#132]
https://github.com/aenix-io/etcd-operator/blob/main/api/v1alpha1/etcdcluster_types.go#L140

etcd cluster pod template has  a member: "PodSpec". 
I seems like this field has same values as https://pkg.go.dev/k8s.io/api@v0.29.3/core/v1#PodSpec

Why doesn't use official package's struct, you defined by original?
If there is no specific reason, I think should import and use official package's struct

**Comment by sergeyshevch** [comment]
Initially, the spec was inspired by the Victoriametrics operator and highly changed by the maintainers team. 

Our type gives us the ability to disable the propagation of some fields. Also, we can make sure that podSpec will work correctly in all K8s versions that the operator should support.

If you need some fields that are now not presented in our podSpec, please rise an issue and we will add it.

**Comment by Bo0km4n** [comment]
I figured out your background, thank you.

The cluster controller create or update etcd pods from above PodSpec, so it should replace spec type to k8s core v1.
By doing so, you can notice new pod spec feature and deprecated it when update k8s dependencies.
I will contribute about this!

**Comment by lllamnyp** [comment]
Thanks for your suggestion. The maintainers are divided in opinions on this matter. I would encourage you to offer your viewpoint under #172.

**Comment by lllamnyp** [comment]
This is completed by #175. Let us know what you think and feel free to comment or open a new issue if you feel that there's more work to be done in this direction.
