### ISSUE TITLE
Design and implement RBAC switcher

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#195]
Following up https://github.com/aenix-io/etcd-operator/issues/76

We need to implement flag that enables or disables mTLS auth in etcd, the [way](https://github.com/clastix/kamaji-etcd/blob/0536a5452d074022edfd5647040d14ee30539aaf/charts/kamaji-etcd/templates/etcd_job_preinstall_2.yaml#L39) it is doing Kamaji:

```bash
if etcdctl user get root &>/dev/null; then
  echo "User already exists, nothing to do"
else
  etcdctl user add --no-password=true root &&
  etcdctl role add root &&
  etcdctl user grant-role root root &&
  etcdctl auth enable
fi

```

**Comment by Kirill-Garbar** [comment]
Duplicates https://github.com/aenix-io/etcd-operator/issues/160
