### ISSUE TITLE
CI: Permissions problem on publishing docker image

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#22]
I just tried to publish tag `v0.0.0` on this PR https://github.com/aenix-io/etcd-operator/pull/21, and got the error:

https://github.com/aenix-io/etcd-operator/actions/runs/8292778100/job/22694650154

Our project settings have no oportunity to enable write permisions via UI

![Screenshot 2024-03-15 at 8 43 23](https://github.com/aenix-io/etcd-operator/assets/7556217/ecfff213-d570-4fc7-af21-ff5a5bba1a48)

So it seems should be solved via [pipeline's YAML](https://github.com/docker/build-push-action/issues/687#issuecomment-1651816012)
@hiddenmarten could you please elaborate?

**Comment by hiddenmarten** [comment]
Sure, I will do it today.
