### ISSUE TITLE
Write instructions how to run controller locally

### ISSUE THREAD

**Issue by sircthulhu** [aenix-io/etcd-operator#23]
We need to write section in doc explaining how to run project in local Kind cluster.
currently blocked by #11 

Steps to run projects:
- `kind create cluster`
- switch kubectl context to kind (important! otherwise you can damage production cluster)
- install cert-manager using helm or kustomize [cert-manager documentation](https://cert-manager.io/docs/installation/helm/)
- `make docker-build` to build docker image with tag `controller:latest`
- `kind load docker-image controller:latest` to load image into cluster
- `make install` (this installs CRD)
- `make deploy` (this deploys controller, roles, certificates)

After making changes in code to redeploy them run
- `make docker-build`, this will regenerate manifests and build image
- `make deploy` to change YAML manifests if necessary
- `kubectl rollout restart -n etcd-operator-system deploy/etcd-operator-controller-manager`

**Comment by Kirill-Garbar** [comment]
```
docker tag controller:latest ghcr.io/aenix-io/etcd-operator:latest
kind load docker-image ghcr.io/aenix-io/etcd-operator:latest
```
instead of
`kind load docker-image controller:latest`
