### ISSUE TITLE
E2e tests and pipeline

### ISSUE THREAD

**Issue by hiddenmarten** [aenix-io/etcd-operator#27]
We discussed internally the need to implement end-to-end (E2E) tests and establish a pipeline for them on pull requests (PRs). To initiate the pipeline, we could use a specific keyword in the commit message or manually trigger it within GitHub.

**Comment by kvaps** [comment]
> To initiate the pipeline, we could use a specific keyword in the commit message or manually trigger it within GitHub.

How about using labels in GitHub?
