### ISSUE TITLE
make defaults for Image Pull Policy = Always

### ISSUE THREAD

**Issue by gecube** [aenix-io/etcd-operator#46]

**Comment by AlexGluck** [comment]
Why not `IfNotPresent`?

**Comment by gecube** [comment]
Because you can not guarantee that on the other side it would be immutable tag.

**Comment by AlexGluck** [comment]
Correct behavior is to use digest instead of `ImagePullPolicy=always`

**Comment by kvaps** [comment]
I have concerns about defaulting `ImagePullPolicy=always` as this will be blocking pod to start in case if registry is now available at the moment

**Comment by sergeyshevch** [comment]
For now default for ImagePullPolicy=IfNotPresent as in kubernetes defaults. Also you can set your value in podSpec field
https://github.com/aenix-io/etcd-operator/blob/main/api/v1alpha1/etcdcluster_types.go#L107

@gecube Looks like we can close this one
