### ISSUE TITLE
Implement ".spec.storage"

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#49]
Internally we agreed to extend spec like this:

```diff
 ---
 apiVersion: etcd.aenix.io/v1alpha1
 kind: EtcdCluster
 metadata:
   name: test
   namespace: ns1
 spec:
   image: "quay.io/coreos/etcd:v3.5.12"
   replicas: 3
+  storage:
+    persistence: true # default: true, immutable
+    storageClass: local-path
+    size: 10Gi
 status:
   conditions:
   - lastProbeTime: null
 	lastTransitionTime: "2024-03-06T18:39:45Z"
 	status: "True"
 	type: Ready
```

**Comment by kvaps** [comment]
There were also an idea of reuisng [`VolumeSource`](https://github.com/kubernetes/api/blob/5147c1a32f6a0b9b155bb84e59f933e0ff8a3792/core/v1/types.go#L49) type.

But there were some concerns about security and stability, eg. user can use `hostPath` volumes and compromise the system.

**Comment by Kirill-Garbar** [comment]
I didn't get how it can be our problem if user defines hostPath. Usually k8s admins create policies (old PSP, kyverno, OPA gatekeeper) to prevent k8s users from creation unwanted (compromising) pod settings (privileged, hostNetwork, hostPath, etc
..)
If we want to help with it, we can add it to validation webhook - allow only some of the volume types. But again, I think it is not our decision to make for the user.

**Comment by kvaps** [comment]
How about creating custom type, with selecting only specific methods we want to support?

**Comment by sircthulhu** [comment]
I think we should use `spec.storage` field from proposal #62

**Comment by gecube** [comment]
I just understood that we can use storage field for zero downtime migration of etcd from one storage to another. @kvaps What do you think?

**Comment by kvaps** [comment]
> I think we should use spec.storage field from proposal https://github.com/aenix-io/etcd-operator/issues/62

Agree

> I just understood that we can use storage field for zero downtime migration of etcd from one storage to another.

Sounds like an additional option
