### ISSUE TITLE
Move defaulting from webhooks to CRD

### ISSUE THREAD

**Issue by kvaps** [aenix-io/etcd-operator#51]
Consider replacing defaulting webhook with native CRD validation:

https://github.com/aenix-io/etcd-operator/blob/94c538dbc1e500bed42f5a0ff21edb5324b2690f/api/v1alpha1/etcdcluster_webhook.go#L45-L47

https://github.com/aenix-io/etcd-operator/blob/94c538dbc1e500bed42f5a0ff21edb5324b2690f/api/v1alpha1/etcdcluster_types.go#L33

**Comment by kvaps** [comment]
Also shouldn't we use pointers for those values to explicitly specify value if it wasn't specified?

**Comment by sircthulhu** [comment]
After tests I found out annotation ` // +kubebuilder:default:=3 ` only adds data to CRD, it does not protect us from creating CR EtcdCluster with zero replicas

**Comment by kvaps** [comment]
It's okay, I think we're should have an opportunity to start with 0
