### ISSUE TITLE
Validate extraArgs field in kind:EtcdCluster

### ISSUE THREAD

**Issue by sergeyshevch** [aenix-io/etcd-operator#77]
We should validate extraArgs field and prevent usage of args generated by operator itself.
Follow up for #72 #69

**Comment by sircthulhu** [comment]
Should we check that etcd supports such flags or just reject collisions for flags used by operator?

**Comment by sergeyshevch** [comment]
The initial request was just to reject collisions. I guess it will be enough for now

**Comment by andreykont** [comment]
Which of 3 behavior  we want:
1. Validation web hook
2. status error
3. skip the unwanted argument

**Comment by sergeyshevch** [comment]
I guess validation webhook error

**Comment by andreykont** [comment]
[](https://github.com/aenix-io/etcd-operator/pull/99)
