### ISSUE TITLE
Problem with pod restart stability

### ISSUE THREAD

**Issue by andreykont** [aenix-io/etcd-operator#98]
Standard life cycle implies that any members may be restarted. 

**How to reproduce:**
Restart any pod 

Log: 
{"level":"fatal","ts":"2024-03-31T06:04:27.129434Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"member 21cdb8e5d2d72088 has already been bootstrapped","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\tgo.etcd.io/etcd/server/v3/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\tgo.etcd.io/etcd/server/v3/etcdmain/main.go:40\nmain.main\n\tgo.etcd.io/etcd/server/v3/main.go:31\nruntime.main\n\truntime/proc.go:250"}

**Comment by sircthulhu** [comment]
Main problem is resolved in #94, the second problem is the usage of emptyDir. If pod is deleted, all it's data is lost and it can't rejoin as there's already member with such name

**Comment by sircthulhu** [comment]
resolved in #94
